<?php
require_once '../config.php';

header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: POST');
header('Access-Control-Allow-Headers: Content-Type');

if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    http_response_code(405);
    echo json_encode(['error' => 'Method not allowed']);
    exit;
}

try {
    $input = json_decode(file_get_contents('php://input'), true);
    $students = $input['students'] ?? [];
    $filters = $input['filters'] ?? [];
    
    if (empty($students)) {
        http_response_code(400);
        echo json_encode(['error' => 'No student data provided']);
        exit;
    }
    
    // Create a proper CSV file with correct headers
    $filename = 'Finote_Selam_Students_' . date('Y-m-d_H-i-s') . '.csv';
    
    // Set correct headers for CSV download that Excel can properly open
    header('Content-Type: text/csv; charset=utf-8');
    header('Content-Disposition: attachment; filename="' . $filename . '"');
    header('Cache-Control: no-cache, must-revalidate');
    header('Expires: 0');
    
    // Open output stream
    $output = fopen('php://output', 'w');
    
    // Add UTF-8 BOM for proper Excel encoding
    fputs($output, "\xEF\xBB\xBF");
    
    // Write header row with correct field names
    $headers = [
        'Student ID',
        'Full Name',
        'Christian Name',
        'Gender',
        'Birth Date',
        'Current Grade',
        'Phone Number',
        'Emergency Phone',
        'Sub City',
        'Living With',
        'Physical Disability',
        'Spiritual Father',
        'Instruments',
        'Registration Date'
    ];
    fputcsv($output, $headers);
    
    // Write data rows with proper field mapping
    foreach ($students as $student) {
        $row = [
            $student['id'] ?? '',
            $student['full_name'] ?? 'N/A',
            $student['christian_name'] ?? 'N/A',
            ucfirst($student['gender'] ?? 'N/A'),
            $student['birth_date_formatted'] ?? ($student['birth_date'] ?? 'N/A'),
            $student['current_grade'] ?? 'N/A',
            $student['phone_number'] ?? 'N/A',
            $student['emergency_phone'] ?? 'N/A',
            $student['sub_city'] ?? 'N/A',
            !empty($student['living_with']) ? ucfirst(str_replace('_', ' ', $student['living_with'])) : 'N/A',
            (!empty($student['physical_disability']) && $student['physical_disability'] !== 'የለም' && $student['physical_disability'] !== 'None') ? $student['physical_disability'] : 'None',
            ($student['has_spiritual_father'] ?? false) ? 'Yes' : 'No',
            !empty($student['instruments']) && is_array($student['instruments']) ? implode(', ', $student['instruments']) : 'None',
            date('Y-m-d H:i:s')
        ];
        fputcsv($output, $row);
    }
    
    // Add compact summary section
    fputcsv($output, []); // Empty row
    fputcsv($output, ['=== REPORT SUMMARY ===']);
    fputcsv($output, ['Total Students:', count($students)]);
    fputcsv($output, ['Export Date:', date('Y-m-d H:i:s')]);
    fputcsv($output, ['Generated By:', 'Finote Selam Sunday School System']);
    
    // Add applied filters if any
    if (!empty($filters) && array_filter($filters)) {
        fputcsv($output, []); // Empty row
        fputcsv($output, ['=== FILTERS APPLIED ===']);
        foreach ($filters as $key => $value) {
            if (!empty($value) && $value !== '') {
                $filterName = ucfirst(str_replace(['_', 'With'], [' ', ' With'], $key));
                fputcsv($output, [$filterName . ':', $value]);
            }
        }
    }
    
    fclose($output);
    exit;
    
} catch (Exception $e) {
    http_response_code(500);
    header('Content-Type: application/json');
    echo json_encode([
        'success' => false,
        'error' => 'Export error: ' . $e->getMessage()
    ]);
}
?>